"""Initial schema: stores, products, history, rules, notifications, executions.

Hand-written rather than autogenerated so the six shared enum types are created exactly
once. ``availability`` is used by three tables; letting each column create its own type
would fail on the second table.

Revision ID: 0001
Revises:
Create Date: 2026-09-01
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ``create_type=False`` keeps column definitions from re-issuing CREATE TYPE; the types
# are created explicitly once in upgrade().
def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


AVAILABILITY = _enum("availability", "in_stock", "out_of_stock", "unavailable", "unknown")
TRACKING_STATUS = _enum("tracking_status", "active", "paused")
RULE_TYPE = _enum(
    "rule_type",
    "price_changed",
    "price_dropped",
    "price_increased",
    "price_below_target",
    "became_available",
    "became_unavailable",
)
CHECK_STATUS = _enum("check_status", "success", "failed", "partial", "skipped")
FETCH_METHOD = _enum("fetch_method", "http", "browser", "none")
NOTIFICATION_STATUS = _enum("notification_status", "pending", "sent", "failed", "suppressed")

ALL_ENUMS = (
    AVAILABILITY,
    TRACKING_STATUS,
    RULE_TYPE,
    CHECK_STATUS,
    FETCH_METHOD,
    NOTIFICATION_STATUS,
)

MONEY = sa.Numeric(12, 2)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)

    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(64), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("domains", postgresql.JSONB(), nullable=False),
        sa.Column("adapter_key", sa.String(64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_stores"),
        sa.UniqueConstraint("slug", name="uq_stores_slug"),
    )

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_canonical", sa.Text(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("product_identifier", sa.String(128), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("current_price", MONEY, nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        sa.Column("availability", AVAILABILITY, server_default="unknown", nullable=False),
        sa.Column("extra_metadata", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("tracking_status", TRACKING_STATUS, server_default="active", nullable=False),
        sa.Column("check_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_products"),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name="fk_products_store_id_stores", ondelete="RESTRICT"
        ),
        sa.UniqueConstraint("url_canonical", name="uq_products_url_canonical"),
        sa.CheckConstraint(
            "check_interval_seconds IS NULL OR check_interval_seconds >= 60",
            name="ck_products_check_interval_minimum",
        ),
    )
    op.create_index("ix_products_store_id", "products", ["store_id"])
    op.create_index("ix_products_tracking_status", "products", ["tracking_status"])
    op.create_index("ix_products_last_checked_at", "products", ["last_checked_at"])

    op.create_table(
        "check_executions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", CHECK_STATUS, nullable=False),
        sa.Column("fetch_method", FETCH_METHOD, server_default="none", nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("extracted_price", MONEY, nullable=True),
        sa.Column("extracted_currency", sa.String(3), nullable=True),
        sa.Column("availability_result", AVAILABILITY, nullable=True),
        sa.Column("price_changed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("availability_changed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("rules_evaluated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rules_matched", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notifications_created", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("error_type", sa.String(64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_check_executions"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name="fk_check_executions_product_id_products",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name="fk_check_executions_store_id_stores",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        "ix_check_executions_product_id_started_at",
        "check_executions",
        ["product_id", "started_at"],
    )
    op.create_index("ix_check_executions_status", "check_executions", ["status"])

    op.create_table(
        "price_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", MONEY, nullable=False),
        sa.Column("currency", sa.String(3), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("check_execution_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_price_history"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name="fk_price_history_product_id_products",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["check_execution_id"],
            ["check_executions.id"],
            name="fk_price_history_check_execution_id_check_executions",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint("price >= 0", name="ck_price_history_price_non_negative"),
    )
    op.create_index(
        "ix_price_history_product_id_observed_at", "price_history", ["product_id", "observed_at"]
    )

    op.create_table(
        "availability_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("availability", AVAILABILITY, nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("check_execution_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_availability_history"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name="fk_availability_history_product_id_products",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["check_execution_id"],
            ["check_executions.id"],
            name="fk_availability_history_check_execution_id_check_executions",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        "ix_availability_history_product_id_observed_at",
        "availability_history",
        ["product_id", "observed_at"],
    )

    op.create_table(
        "tracking_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("rule_type", RULE_TYPE, nullable=False),
        sa.Column("params", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("notify_provider", sa.String(32), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=True),
        sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_tracking_rules"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name="fk_tracking_rules_product_id_products",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "cooldown_seconds IS NULL OR cooldown_seconds >= 0",
            name="ck_tracking_rules_cooldown_non_negative",
        ),
    )
    op.create_index(
        "ix_tracking_rules_product_id_enabled", "tracking_rules", ["product_id", "enabled"]
    )

    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("tracking_rule_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(64), nullable=False),
        sa.Column("dedupe_key", sa.String(128), nullable=False),
        sa.Column("payload", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("status", NOTIFICATION_STATUS, server_default="pending", nullable=False),
        sa.Column("provider", sa.String(32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_notifications"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name="fk_notifications_product_id_products",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tracking_rule_id"],
            ["tracking_rules.id"],
            name="fk_notifications_tracking_rule_id_tracking_rules",
            ondelete="SET NULL",
        ),
        # The uniqueness that makes notification delivery idempotent.
        sa.UniqueConstraint("dedupe_key", name="uq_notifications_dedupe_key"),
    )
    op.create_index(
        "ix_notifications_product_id_created_at", "notifications", ["product_id", "created_at"]
    )
    op.create_index("ix_notifications_status", "notifications", ["status"])


def downgrade() -> None:
    op.drop_table("notifications")
    op.drop_table("tracking_rules")
    op.drop_table("availability_history")
    op.drop_table("price_history")
    op.drop_table("check_executions")
    op.drop_table("products")
    op.drop_table("stores")

    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
